version: 3
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache
  skip-files:
    - \cmd\main.go
    - \.pb\.go$
    - \.pb\.gw\.go$

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2
  gosec:
    excludes:
      - G115
      - G304
  

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - revive
    - unused

issues:
  exclude-use-default: false
  exclude:
    - G104
    - G115
    - G304
    - exported func .* returns unexported type .*, which can be annoying to use
    - don't use an underscore in package name
  exclude-rules:
    - path: cmd/*
      linters:
        - all