volumes:
  postgres_volume:
  redis_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    env_file:
      - ".env"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_volume:/data
    command: redis-server --save 60 1 --loglevel warning
