services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./configs:/app/configs

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./configs:/app/configs

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: 