- url: http://backend:8002
- url: http://backend:8003
- url: http://backend:8004
- url: http://backend:8005
- url: http://backend:8006
- url: http://backend:8007
- url: http://backend:8008
- url: http://backend:8009
- url: http://backend:8010
- url: http://backend:8011
- url: http://backend:8012
- url: http://backend:8013
- url: http://backend:8014