http:
  listen_port: 8080
  read_timeout: 10
  write_timeout: 10

balancer:
  strategy: round_robin # round_robin, random
  backends_file: configs/backends.yaml
  health_check_interval: 60s

logger:
  log_level: debug # debug, info, warn, error
  log_format: text # json, text
  log_output: stdout # stdout, stderr, file

retry:
  max_attempts: 3
  delay: 500ms
  max_delay: 3s